### PR TITLE
Migrated most pages

### PR DESCRIPTION
**Pull request by moizhusnain**

### CODE REVIEW

**Comment by mahahahaham** [comment]
@moizhusnain 

Done for today. Main Headings and stuff are mainly dealt with except for device SDK. Baki andar ka kaam rehta hae. I'll create tabs, add leftover images and complete the editing tomorrow In Shaa Allah. 

1. In the client SDK I have named files in 2 ways. Tell me which one works for us. 
Screenshot 2022-06-30 at 11 54 22 PM

2. You have to see whether we can add sections like these under one heading. (Reference to a conversation I hope you remember)
Screenshot 2022-06-30 at 11 58 02 PM

3. The datastore section is a complete mess. Or I feel like it is. It is. 

4. I do not remember anything else. Should have written down sath sath.

**Comment by moizhusnain** [comment]
Don't use `'` in the file name. It is messing up the build.

Screenshot 2022-07-01 at 4 02 32 AM

**Comment by moizhusnain** [comment]
> @moizhusnain 
> 1. In the client SDK I have named files in 2 ways. Tell me which one works for us.

I guess the second option is better, because unlike guides, here we want it easier for developers to quickly skim through and find right function.

**Comment by moizhusnain** [comment]
You gotta complete the migration so that I could review it at once. Hopefully, we will done with it by tomorrow. Ps I will brief you about datastore tomorrow.

**Comment by moizhusnain** [comment]
I couldn't got a chance to review the entire thing, but I have made some fixes for the sidebar. Here are some of the changes that I have made

1. Improved the style of the sidebar a bit. The directories at the root are now being displayed in upper case i.e. guides heading is now in upper case. Files inside the root directories are not indented i.e. guides and auth will be displayed without indentation. But we are indenting the files inside i.e. the files inside guides -> auth are indented by 10px. Hope it makes sense 😂 But it is gonna look better I promise. I may make few more edits to the design
2. One of the with current side bar has been sorting. With this update I have included way to sort files as per our wish. Now you can include `sort.json` file in a directory to instruct compiler about the sorting in layout. Check `sort.json` file in root.

Some fixes that I have made for your reference (and for my OCD 🤦‍♂️) but in future, I will only make recommendations instead of directly making changes)
1. It is `FAQs` instead of `FAQ's` and we don't need to put inside a directory.
2. We don't need to call `canvas` as `grandeur canvas`. I renamed the directory inside guides. 
3. We don't need to call `datastore` as `grandeur datastore`. I renamed it in meta.json
4. It can simply `Auth` instead of `Auth()`
5. `user-and-administration` page can be moved inside security, because it is about security.
6. Networking and Hardware files aren't required to be placed in a directory (unless we add more pages).
7. Keywords aren't required to be placed inside a directory.

**Comment by moizhusnain** [comment]
Some recommendations
1. We can break canvas guide page into two files, build and run.
2. Make it simple `Canvas` in references. And we don't need to append widget with every widget name.
3. We don't folders when there is just one file inside. Like in case of CLI, or are we planning to add more pages? I think we can add more pages
4. Now since we have tabs, so we can have single page for different languages inside Initialization and Installation
5. Drop `'` with `Client SDK's` and `Device SDK's`
6. Instead of having a separate folder `Reference Documentation`. Move init to Initialization and move classes outside. We can move Initialization and Installation in a separate `Getting Started` folder.

**Comment by moizhusnain** [comment]
Here is what is due on me

1. Detailed review of content. I have some ideas for getting started section.
2. Video component
3. Better side bar

Things due on you
1. Make some of the fixes that I recommended and let me know about your thoughts.
2. Add datastore documentation

LFG 🎉

**Comment by mahahahaham** [comment]
> 

1 and 2 - Done
3- Yes we can add more pages. We haven't discussed this section yet.
4- We are already doing that. There's a single page for both.
5- Done.
6 and 7 - Working on it.

**Comment by moizhusnain** [comment]
Don't worry, I won't be this brutal on other pages. I swear 😅

**Comment by moizhusnain** [comment]
The extra dash after in
> [FIX] This is where Grandeur comes in- a tech-smart

The space after comma
> [FIX] With minimal engineering time,your apps

In getting started page, instead it can be pair device with account
> [FIX] Pair the account with the device

In the getting started, the steps still seems like a lot because we are breaking each step into so many individual steps. It is like, looking a lot. What if we first list the sub steps in bullets and combine the image in video at the end of each step. I mean the sub steps in itself are quite enough, but we can still keep the video for extra context. It will give it more concise look and feel. Something similar to https://university.webflow.com/lesson/intro-to-the-editor

Instead of just specifying that it is important to copy the token, we can actually say that it will help us in connecting the device to Grandeur (and link to building first application).
> [FIX] Do not forget to copy them both somewhere as they will be imperative for use later and won't be accessible after closing the dialogue box.

We can describe the project a bit after the heading. Like explain what it is for. Here project is meant to be a workspace for developer. All the devices data will be contained in it. Similarly define why we are creating device (it is meant to securely connect devices to cloud) and users (like the users here are end users, who will be using the device in production). And we are pairing device to a user so that only the user or the admin of the project can access the data (like an extra security measure). You can give a real world example here, like how you would only like the end user who bought the smart light from you to connect to it. Just a bit of detail is required, we can then redirect user to guide about the topic.
> [FIX] Create a project

Setup the Canvas in next step, like in the step where you are building first IoT application.
> [FIX] The button widget is ready.

The larger feedback here, we know there are guides and stuff. In getting started tutorials, we want to be concise, but we also don't want to withhold way too much information from user. It is a balance.

**Comment by moizhusnain** [comment]
Truly understand the potential of Grandeur, as in, people already understand potential of IoT. They are here to understand Grandeur.
> [FIX] In order to truly understand the potential of IoT

By following the getting started guideline
> [FIX] following this tutorial here

There is just one hardware component, duh 😅 May be we don't need this. If you would like to include, then may be create a list and link to the component on sparkfun or something similar site (like hackster).
> [REVISIT] Hardware Components

Explain that we are using Arduino in this tutorial. Users are dumb. Then probably add a link to tutorial on downloading arduino 😅
> [FIX] Setting up the Arduino Environment

May be move board selection to guides > hardware and simply link here. Put more emphasis on installing grandeur library. You can add a video. 

We can potentially also add a little section in getting started, where we can explain that now you can download the library for your specific microcontroller to connect your hardware to grandeur. Add list of supported arch, like esp8266 with Arduino, esp32 with Arduino and (most) Linux based SOCs with Python (tested on Respberry Pi). With link to SDK references. 

Additionally, we can point users to hello world page at the end of getting started guide. You can say something like let's code our first hardware device in this tutorial.

And you should have used h3 here, instead of making it bold (I changed it in my commit)
> Board Selection

Don't use a lot of italic. Personal preference, i feel little dizzy after witnessing a differently emphasised text in a single sentence. And add content between two headings. Like after "Setting up the Arduino Environment" heading, add some content before beginning the board selection heading. Again, personal preference.

We don't need the link anymore
> [REMOVE] Download the 

And replace code. And add link for reference.
> [FIX] Forgot how to do it

Why don't we add the serial monitor output here. Like a screen recording. With tiny bubble for hardware video.
> [FIX]  Once it's connected, it prints that in the terminal.

And move Canvas to this screen. You may also want to include some description about the code. Like the state diagram.

**Comment by moizhusnain** [comment]
Loved your updates 👏 everything is on point.

Moving on

You can add link for esp on on hello world page
> `ESP8266 - Espressif Wemos D1 Mini`

On hello world page, this para seems like a bit extra (or misplaced). But honestly I loved the paragraph. It is just seems bit misplaced.
> Just like internet makes the world 

Now here you can put bit of the background, like Grandeur run on top of esp8266 to help you store data on cloud and transfer data from device to a user
> With Software Development Kits (SDKs) like Grandeur's, you can directly program the ESP8266’s on-chip Microcontroller to blink the LED.

Update the code block as it won't run with canvas for (because of const char* issue). Also change %d to %s
> ```cpp
> void updateHandler(const char* path, int state) {
>    /* Print state */
>    Serial.printf("Updated state is %d\n", state);
>
>...
>```

Don't include the `packages.json` file, because it is not related to Arduino 
> This is how your package.json file should look:

Add link to quick start
> Forgot how to do it?

Explain the code logic a bit

Until we don't create the full demo, you can just link the demo of canvas and the serial monitor of arduino. 
> A Canvas guide is also lsited below.

Include the link of last step
> We've already accomplished the task of blinking the on-board LED of ESP8266

Remove the borders of images in custom app pages (except the one) and decrease font size.

Similar to canvas demo, add serial monitor with the custom app demo.

And use callout instead of block quote

**Comment by moizhusnain** [comment]
Moving on

What if we don't include the headings in managing project guide? I means, may be just a line or two about the step is fine. What are your thoughts?

May be iterate on the words on api key page 😅
> Each project is identified by a digital signature that we call the API key, just as your identification card or social security identifies you as a citizen.

Iterate on the wording (api key page)
> our project's API Key then delegates your project's access to the SDKs

Label the code example on api key page, like what's the language?

No H1 on register user page.

Redundant line
> You can also create a user to delegate the access. 

Explain user as like, you need custom applications and you want your end users to use your apps securely. That's where this whole auth concept comes.

Consolidate register user and create user step. I mean, they are both just two ways of doing same things. First demonstrate dashboard step, then show how it can be done with code (and label your code).

Again on login page, write the guide from dashboard first pov. So we don't need
> auth.login(email, password)

You can describe it as, once you are done with creating the account, you can go ahead and use SDKs to login user. How about consolidating the SDKs based pages into one managing user page? And don't use the dashboard demo for login and logout (instead use the custom app demo), it is confusing.

In Canvas, we can have just one page, Widgets. The intro for canvas is amazing. Also explain the variable like the global global variable concept, you can have a tiny little heading on widget page to explain several inputs. Like for now we can have a consolidated view of possible inputs for every widget. As in the variable and name fields are configurable in every widget, while the other inputs are available for certain widgets. Let's discuss. (Check parameters list for __init__ on https://websocket-client.readthedocs.io/en/latest/app.html for reference)

Where is the register device (or like manage device)? We can rename device data to simply data. Now we also have option to view device data from dashboard directly. We can again refer to the global variable logic. We can also include a bit of graphic to show device data. Link to reference.

We want to move away from the namespace logic, it is old. We need much simple words. Another idea is to include more callouts in guides, to highlight core definitions. 

We don't do this anymore
> When you pair a device with a user account, an access token is generated for the device. This token is what the device uses to connect to Grandeur. 

First show the demo, then code. (like you can also do this from code, which help you in production use cases, like users can pair to their devices on their own).

Again for datastore, you are heavily relying on code. Less code more dashboard. Like each of the step in collections and querying page is possible with the dashboard. We want guides for definitions. We can have a page on how data is organized in collections. Then we can have a a page on managing data (where we can the link all the CURD operations). With each operation, we will add a demo (and additionally include code, with link to references).

We need the new definition for Access Credentials. Like now the Access Key Token pair is meant for authorization. Simlarly, we want to make CORS important (but less scary). You can use wording like CORS rule only allow the whitelisted domain to communicate, it is another way we protect you site data access. Then link to CORS topic on mdn (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

On hardware page, add a bit of meta information before starting the subheadings, looks more aesthetic. We never really tested it on wifi shield 😂 And remove `myProject`. Fix the space after code segments in handling connection status heading.

And we can make the headings a bit concise. Like 
> Handling Connection and Disconnection with Grandeur

can become `Handling connection status with Grandeur` 

Label code. We can divide hardware page into multiple pages. Like one for installing board. Others for each demo code that you have included. Revisit hardware page in general, many things can be improved.

Remove networking page. Not working out here. We will include more details in future, with proper architecture level diagrams.

One important guideline here (something that I have noticed over and over again): it is your job to keep the language style similar. Every section of the document should feel coherent. Similar design language across the whole documentation. Think about everything. You are the owner of docs at Grandeur.

**Comment by moizhusnain** [comment]
Include videos for cli documentation. Refer to repository. The other way to install the cli is to visit the releases page on Github repository. Describe a bit, like why we created this cli. It acts as a layer on top of Arduino to make it easier for developers to work with ESP8266 and ESP32.

Use list in common widget settings (canvas). How about adding tiny demo videos for each operation? In each widget, treat `Min/Max Values` as two options. Include table widget. And add tiny demo videos to demonstrate the function of each widget.

I figured out why the code sometimes don't render. Use different group id for client and hardware based code segments. You select `py` from hardware based code segment and go to js section and figure out the code is not rendering (which happens because by design the tabs component try to find the selected tab and renders nothing). I fixed the bug, but it is not a full solution.

For commands, use `bash` language selector (as in, for styling the code, pretty much how you specific cpp and js). The language selector for react is `jsx`.

How about we don't use the parenthesis in function name (in page title)? 

How about we also add a table for possible response codes? 

The left centre right  in table is triggering my OCD. We can keep it left.

Similarly we don't need the augments in title. Like we can just make `auth.register(email, password, displayName, phone)` as register (we can keep the parenthesis in menu / page title). And it is not H1. Make first heading as H1.

On register page, in the code example, it should be `AUTH-ACCOUNT-REGISTRATED`
> AUTH-ACCOUNT-REGISTRATION

Don't repeat my mistake. Copy after careful review, that's your core job.

We don't need to handle the response for `on` anymore. Just complicates the code
> ```js
> then((res) => {
>   // Call to onDevicesList returns the
>   // clear method as a response to promise 
>   switch(res.code) {
>     case "TOPIC-SUBSCRIBED": 
>       // Event has been subscribed
>       listener = res;
>   }
> });
> ```

Don't need this paragraph
> It is important to note that the update will be directly sent without a response code. So for example whenever a new device will be paired, entire list will be sent as the argument in form an array.

How about instead using the switch case, let's just simply use if statements? Will result in more clean code.

Docs are needed to be coherent. ie we are not using this scheme in client sdk
> ```cpp
> // **RESULT**
> // Includes the SDK in your sketch and defines the global object grandeur.
>```

Similarly we don't have `The Dexterity of Arduino SDK` section in client SDK. I understand the purpose. We can do this differently. We need serious fixes in this section.

We don't have the project sub dir for client sdk. And we are not quoting the code usage with title
> insert (documents: Var, callback: Callback) : returns void

Similarly, why aren't you creating a directory a collection in device sdk, similar to client sdk. The concept is, we gotta make it as coherent as possible.

**Comment by moizhusnain** [comment]
Overall, it is phenomenal work. Your speed and writing style is amazing 🔥

**Comment by moizhusnain** [comment]
@oyesameed can you help me design the sidebar of the docs?

**Comment by mahahahaham** [comment]
> Loved your updates 👏 everything is on point.
> 
> Moving on
> 
> You can add link for esp on on hello world page
> 
> > `ESP8266 - Espressif Wemos D1 Mini`
> 
> On hello world page, this para seems like a bit extra (or misplaced). But honestly I loved the paragraph. It is just seems bit misplaced.
> 
> > Just like internet makes the world
> 
> Now here you can put bit of the background, like Grandeur run on top of esp8266 to help you store data on cloud and transfer data from device to a user
> 
> > With Software Development Kits (SDKs) like Grandeur's, you can directly program the ESP8266’s on-chip Microcontroller to blink the LED.
> 
> Update the code block as it won't run with canvas for (because of const char* issue). Also change %d to %s
> 
> > ```c++
> > void updateHandler(const char* path, int state) {
> >    /* Print state */
> >    Serial.printf("Updated state is %d\n", state);
> > 
> > ...
> > ```
> 
> Don't include the `packages.json` file, because it is not related to Arduino
> 
> > This is how your package.json file should look:
> 
> Add link to quick start
> 
> > Forgot how to do it?
> 
> Explain the code logic a bit
> 
> Until we don't create the full demo, you can just link the demo of canvas and the serial monitor of arduino.
> 
> > A Canvas guide is also lsited below.
> 
> Include the link of last step
> 
> > We've already accomplished the task of blinking the on-board LED of ESP8266
> 
> Remove the borders of images in custom app pages (except the one) and decrease font size.
> 
> Similar to canvas demo, add serial monitor with the custom app demo.
> 
> And use callout instead of block quote

I forgot to push the final updates I made so you technically reviewed the rough draft again. :(

**Pull request merged**
